// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  pinataIcon: require('../Images/pinata.png'),
  profileIcon: require('../Images/profileIcon.png'),
  lotteryImg: require('../Images/lotteryImg.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  backgroundVideo: require('../Images/bgVideo.mp4'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backBtn: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  facebookLoginButton: require('../Images/fbloginbtn.png'),
  phoneLoginButton: require('../Images/phoneLoginbtn.png'),
  backButton: require('../Images/backbtn.png'),
  howtoButton: require('../Images/howto.png'),
  faqButton: require('../Images/faq.png'),
  submitButton: require('../Images/submit.png'),
  gethelpButton: require('../Images/gethelp.png'),
  rateusButton: require('../Images/rateus.png'),
  twitterButton: require('../Images/twitter.png'),
  instagramButton: require('../Images/instagram.png'),
  facebookButton: require('../Images/facebook.png'),
  closeBtn: require('../Images/closeBtn.png'),
  gift: require('../Images/gift.png'),
  logo: require('../Images/logo.png'),
}

export default images
